# Generated by Django 5.2.5 on 2025-10-05 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ez a felhasználónév már foglalt.'}, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='A felhasználónév csak kisbetűket, számokat, pontot és aláhúzást tartalmazhat.', regex='^[a-z0-9._]+$')], verbose_name='username'),
        ),
    ]
