# Generated by Django 5.2.5 on 2025-09-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist',
            new_name='user',
        ),
    ]
