# Generated by Django 5.2.5 on 2025-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_category_artwork_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.AddField(
            model_name='artwork',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='artworks/videos/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
