# Generated by Django 5.2.5 on 2025-10-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artist_type',
            field=models.CharField(default='ARTIST', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_full_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
